#include <jni.h>
#include "zsim_hooks.h"
#include "zsim_jni.h"  // generated by javah

JNIEXPORT void JNICALL Java_zsim_roi_1begin(JNIEnv *env, jclass cls) { zsim_roi_begin(); }
JNIEXPORT void JNICALL Java_zsim_roi_1end(JNIEnv *env, jclass cls) { zsim_roi_end(); }
JNIEXPORT void JNICALL Java_zsim_heartbeat(JNIEnv *env, jclass cls) { zsim_heartbeat(); }
